# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Perfunct
# tagline:             'Tech'
description:         'Just whatever'
url:                 http://perfunct.tech
baseurl:             ''
paginate:            5

# Custom vars
version:             1.0.0

github:
  repo: https://github.com/alec-brooks/alec-brooks.github.io
